services:


  # 获取视频地址
  mcp-browser-video:
    image: mcp-browser
    container_name: mcp-browser-video
    restart: always
    # command: --debug
    ports:
      - 5901:5901             # VNC Server
      - 6901:6901             # noVNC Client
      # - 8088:8088             # Mcp-Playwright
      # - 8070:8070             # Mcp-auto-Playwright
    environment:
      - VNC_PW=headless
      - DISPLAY=:0
    networks:
      - default
      - shared-net


  # 获取渠道地址
  mcp-browser-channel:
    image: mcp-browser
    container_name: mcp-browser-channel
    restart: always
    # command: --debug
    ports:
      - 5902:5901             # VNC Server
      - 6902:6901             # noVNC Client
      # - 8088:8088             # Mcp-Playwright
      # - 8070:8070             # Mcp-auto-Playwright
    environment:
      - VNC_PW=headless
      - DISPLAY=:0
    networks:
      - default
      - shared-net


  redis:
    # ref: https://hub.docker.com/_/redis
    image: redis:7-alpine # 7.4.0
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data
    networks:
      - default
      - shared-net


volumes:
  redis:
    name: support_redis


networks:
  default:
  shared-net:
    name: shared-network
    external: true
